package disgo

// Warning: This file has been automatically generated by generate/apimodel/main.go
// Do NOT make changes here, instead adapt model.go and run go generate

import "encoding/json"

type DMChannel struct {
	discordObject *internalDMChannel
}

func (s *DMChannel) MarshalJSON() ([]byte, error) {
	return json.Marshal(s.discordObject)
}

func (s *DMChannel) UnmarshalJSON(b []byte) error {
	return json.Unmarshal(b, &s.discordObject)
}

func (s *DMChannel) ID() Snowflake {
	return s.discordObject.ID
}

func (s *DMChannel) IsPrivate() bool {
	return s.discordObject.IsPrivate
}

func (s *DMChannel) Recipient() *User {
	return s.discordObject.Recipient
}

func (s *DMChannel) LastMessageID() Snowflake {
	return s.discordObject.LastMessageID
}

type User struct {
	discordObject *internalUser
}

func (s *User) MarshalJSON() ([]byte, error) {
	return json.Marshal(s.discordObject)
}

func (s *User) UnmarshalJSON(b []byte) error {
	return json.Unmarshal(b, &s.discordObject)
}

func (s *User) ID() Snowflake {
	return s.discordObject.ID
}

func (s *User) Username() string {
	return s.discordObject.Username
}

func (s *User) Discriminator() string {
	return s.discordObject.Discriminator
}

func (s *User) Avatar() string {
	return s.discordObject.Avatar
}

func (s *User) Bot() bool {
	return s.discordObject.Bot
}

func (s *User) MFAEnabled() bool {
	return s.discordObject.MFAEnabled
}

func (s *User) Verified() bool {
	return s.discordObject.Verified
}

func (s *User) EMail() string {
	return s.discordObject.EMail
}
